name: Terraform Plan (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string
      var-file:
        description: 'Terraform var file'
        required: true
        type: string
      destroy:
        description: 'Create destroy plan'
        required: false
        type: boolean
        default: false
      terraform-version:
        description: 'Terraform version'
        required: true
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        type: string
        default: './terraform'
      aws-region:
        description: 'AWS region'
        required: true
        type: string
      backend-bucket:
        description: 'S3 bucket for state'
        required: true
        type: string
      backend-key:
        description: 'S3 key for state file'
        required: true
        type: string
      backend-region:
        description: 'AWS region for S3 backend'
        required: false
        type: string
        default: ''
      backend-dynamodb-table:
        description: 'DynamoDB table for state locking'
        required: false
        type: string
        default: ''
      pre-step:
        description: 'Custom script to run before plan'
        required: false
        type: string
        default: ''
      post-step:
        description: 'Custom script to run after plan'
        required: false
        type: string
        default: ''
    secrets:
      aws-role-arn:
        description: 'AWS IAM Role ARN for OIDC authentication'
        required: false
      aws-access-key-id:
        description: 'AWS Access Key ID (alternative to OIDC)'
        required: false
      aws-secret-access-key:
        description: 'AWS Secret Access Key (alternative to OIDC)'
        required: false
      # Pass all other secrets from caller using 'secrets: inherit' in caller
    outputs:
      exitcode:
        description: 'Plan exit code'
        value: ${{ jobs.plan.outputs.exitcode }}

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-Plan Step
        if: inputs.pre-step != ''
        shell: bash
        run: ${{ inputs.pre-step }}

      - name: Setup Terraform & AWS
        uses: bridan234/PipelineTemplates/Terraform/AWS/actions/setup@main
        with:
          terraform-version: ${{ inputs.terraform-version }}
          aws-region: ${{ inputs.aws-region }}
          aws-role-arn: ${{ secrets.aws-role-arn }}
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

      - name: Terraform Init
        uses: bridan234/PipelineTemplates/Terraform/AWS/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}
          backend-bucket: ${{ inputs.backend-bucket }}
          backend-key: ${{ inputs.backend-key }}
          backend-region: ${{ inputs.backend-region || inputs.aws-region }}
          backend-dynamodb-table: ${{ inputs.backend-dynamodb-table }}

      - name: Terraform Plan
        id: plan
        uses: bridan234/PipelineTemplates/Terraform/AWS/actions/plan@main
        with:
          working-directory: ${{ inputs.working-directory }}
          var-file: ${{ inputs.var-file }}
          destroy: ${{ inputs.destroy }}
        env:
          # All secrets from caller are available here via 'secrets: inherit'
          # Set them as environment variables for Terraform
          TF_VAR_example_secret: ${{ secrets.EXAMPLE_SECRET }}
          TF_VAR_another_secret: ${{ secrets.ANOTHER_SECRET }}
          # Add more TF_VAR_* as needed

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ inputs.environment }}
          path: ${{ inputs.working-directory }}/tfplan
          retention-days: 5

      - name: Post-Plan Step
        if: inputs.post-step != ''
        shell: bash
        run: ${{ inputs.post-step }}
