name: 'Terraform Plan'
description: 'Run Terraform plan'
inputs:
  working-directory:
    description: 'Working directory for Terraform'
    required: false
    default: './terraform'
  var-file:
    description: 'Terraform var file (e.g., staging.tfvars)'
    required: true
  destroy:
    description: 'Create destroy plan'
    required: false
    default: 'false'
outputs:
  exitcode:
    description: 'Terraform plan exit code'
    value: ${{ steps.plan.outputs.exitcode }}

runs:
  using: 'composite'
  steps:
    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # Note: Environment variables (like TF_VAR_*) are automatically inherited from the workflow
      run: |
        PLAN_ARGS="-var-file=${{ inputs.var-file }} -out=tfplan -detailed-exitcode"
        if [ "${{ inputs.destroy }}" == "true" ]; then
          PLAN_ARGS="$PLAN_ARGS -destroy"
        fi
        terraform plan $PLAN_ARGS
      continue-on-error: true
